#Google Drive Connection

In [2]:
from google.colab import drive
drive.mount('/content/drive')
import os
os.chdir("/content/drive/My Drive/Workspace")
!ls

Mounted at /content/drive
btkMLCourse.ipynb  GoogleMLCrash.ipynb	melb_data.csv	   pandasExercise.ipynb
carPrice.ipynb	   IrisSpecies.ipynb	MelbourneML.ipynb  pythonders.ipynb
Data		   maaslar.csv		merc.csv	   satislar.csv
eksikveriler.csv   maaslar_yeni.csv	odev_tenis.csv	   veriler.csv


# Data Preprocessing

In [38]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [39]:
dataFrame = pd.read_csv("Data/Iris.csv")

In [40]:
dataFrame.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [41]:
dataFrame.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [42]:
dataFrame.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [43]:
dataFrame.drop(columns="Id", axis=1, inplace=True)
dataFrame

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [44]:
le= LabelEncoder()
dataFrame["Species"] = le.fit_transform(dataFrame["Species"])
dataFrame

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [45]:
dataFrame.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
count     150.000000    150.000000     150.000000    150.000000  150.000000
mean        5.843333      3.054000       3.758667      1.198667    1.000000
std         0.828066      0.433594       1.764420      0.763161    0.819232
min         4.300000      2.000000       1.000000      0.100000    0.000000
25%         5.100000      2.800000       1.600000      0.300000    0.000000
50%         5.800000      3.000000       4.350000      1.300000    1.000000
75%         6.400000      3.300000       5.100000      1.800000    2.000000
max         7.900000      4.400000       6.900000      2.500000    2.000000

In [46]:
dataFrame.corr()

SepalLengthCm  SepalWidthCm  ...  PetalWidthCm   Species
SepalLengthCm       1.000000     -0.109369  ...      0.817954  0.782561
SepalWidthCm       -0.109369      1.000000  ...     -0.356544 -0.419446
PetalLengthCm       0.871754     -0.420516  ...      0.962757  0.949043
PetalWidthCm        0.817954     -0.356544  ...      1.000000  0.956464
Species             0.782561     -0.419446  ...      0.956464  1.000000

[5 rows x 5 columns]

## Feature Selection

In [47]:
x= dataFrame.iloc[:,0:4].values
x.shape

(150, 4)

In [48]:
y= dataFrame.iloc[:,-1].values
y.shape

(150,)

In [49]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.4, random_state=5)

In [50]:
x_train.shape

(90, 4)

In [51]:
y_train.shape

(90,)

In [52]:
sc= StandardScaler()

In [53]:
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [54]:
x_test

array([[-6.48443529e-02, -7.75339285e-01,  6.25589211e-02,
        -1.43590299e-03],
       [ 2.85315153e-01, -1.00043779e+00,  1.01971041e+00,
         2.57026636e-01],
       [-6.48443529e-02, -5.50240783e-01,  7.38195269e-01,
         1.54933933e+00],
       [-1.69892204e+00,  3.50153226e-01, -1.40131983e+00,
        -1.29374860e+00],
       [ 1.56923334e+00,  1.25054723e+00,  1.30122556e+00,
         1.67857060e+00],
       [-1.11532287e+00, -1.45063479e+00, -2.75259253e-01,
        -2.59898442e-01],
       [-1.11532287e+00, -1.00043779e-01, -1.34501680e+00,
        -1.29374860e+00],
       [ 5.18754823e-02,  3.50153226e-01,  5.69286182e-01,
         7.73951714e-01],
       [-9.98603034e-01, -1.00043779e-01, -1.23241075e+00,
        -1.29374860e+00],
       [-5.31723693e-01, -1.00043779e-01,  4.00377095e-01,
         3.86257906e-01],
       [-2.98284023e-01, -1.00043779e-01,  4.00377095e-01,
         3.86257906e-01],
       [ 5.18754823e-01, -5.50240783e-01,  7.38195269e-01,
      

## Create Models

In [55]:
def knn(X_train, X_test, Y_train, Y_test, metric):
  Knn = KNeighborsClassifier(metric=metric)
  Knn.fit(X_train, Y_train)

  return confusion_matrix(Y_test,Knn.predict(X_test))

In [56]:
def svm(X_train, X_test, Y_train, Y_test, kernel):
  svm= SVC(kernel=kernel)
  svm.fit(x_train,y_train)

  return confusion_matrix(Y_test, svm.predict(X_test))

In [57]:
def gaussianNb(X_train, X_test, Y_train, Y_test):
  gnb= GaussianNB()
  gnb.fit(X_train,Y_train)
  
  return confusion_matrix(Y_test,gnb.predict(X_test))

In [58]:
def randomForest(X_train, X_test, Y_train, Y_test, estimator, criterion):
  rfc= RandomForestClassifier(n_estimators= estimator, criterion=criterion)
  rfc.fit(X_train,Y_train)

  return confusion_matrix(Y_test, rfc.predict(X_test))

In [59]:
kcm=knn(x_train, x_test, y_train, y_test, metric="minkowski")
svmcm=svm(x_train, x_test, y_train, y_test, kernel="sigmoid")
gnbcm= gaussianNb(x_train, x_test, y_train, y_test)
rfcm= randomForest(x_train, x_test, y_train, y_test, estimator=40, criterion="entropy")

## Result

In [60]:
print("KNN\n",kcm)
print("SVM\n",svmcm)
print("Naive Bayes\n",gnbcm)
print("Random Forest\n",rfcm)

KNN
 [[20  0  0]
 [ 0 21  0]
 [ 0  1 18]]
SVM
 [[20  0  0]
 [ 0 18  3]
 [ 0  1 18]]
Naive Bayes
 [[20  0  0]
 [ 0 20  1]
 [ 0  1 18]]
Random Forest
 [[20  0  0]
 [ 0 20  1]
 [ 0  2 17]]
